Algoritmo "maoir que 10"
// Disciplina   : Logica de programacao com JavaScript
// Professor   : Jailson Costa dos Santos
// Descrição   : verificar se um valor é maior que 10
// Autor(a)    : Bruno Carlos Soares
// Data atual  : 21/03/2024
Var
   valor:inteiro
Inicio
   Escreva("Digite um numero: ")
   leia(valor)
   escreval
   se (valor > 10)entao
      escreval("e maior que 10!")
   senao
      escreva("Nao e maior que 10!")
   fimse
   escreval
Fimalgoritmo