Algoritmo "positivo ou negativo"
// Disciplina   : Logica de programacao com JavaScript
// Professor   : Jailson Costa dos Santos
// Descrição   : verificar se um numero é positivo ou negativo
// Autor(a)    : Bruno Carlos Soares
// Data atual  : 21/03/2024
Var
   valor:inteiro
Inicio
   Escreva("Digite um número: ")
   leia(valor)
   escreval
   se (valor > -1)entao
      escreval("é positivo!")
   senao
      escreva("é negativo!")
   fimse
   escreval
Fimalgoritmo